---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Leo Folder Locker - An easy and freeware folder locker"
keywords:    "leofolderlocker, folderlocker, locker, malikusmanaura, freewarefolderlocker, windowsfolderlocker, fastfolderlocker, officalsiteofleofolderlocker"
description: "Leo FOlder Locker is an easy to use, fast and free folder locker for Windows by Malik Usman Aura"
source_link: "https://github.com/usmanaura47/leo-folder-locker"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key:  ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  red:       '#d9534f'
  grey:      '#343434'
  amethyst:  '#9b59b6'
  asphalt:   '#34495e'
  sea:       '#e74c3c'

kramdown:
  auto_ids:  false
  
  gems: 
    - jekyll-sitemap
