---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Leo Folder Locker - An easy and freeware folder locker"
keywords:    "leo folder locker, folder locker, folder lock windows 7, computer folder lock, folder lock windows 8, my folder lock, secure folder windows 7, folder password windows, malik usman aura, folder protection windows 7 windows 8, freeware folder locker, folder lock windows, protect folder with password windows 7 8 8.1 10, fast folder locker, windows 10 freeware, folder lock computer"
description: "Leo Folder Locker is an easy to use, fast and free folder locker for Windows by Malik Usman Aura"
source_link: "https://github.com/usmanaura47/leo-folder-locker"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-76202959-2 ## put YOUR key here to enable tracking! (blank to disable)

url: https://leofolderlocker.tk   # with the https protocol
enforce_ssl: leofolderlocker.tk

twitter:
  username: malikusmanaura
  image: /img/pic2.png
  
image: 
  path: /img/pic2.png

logo: /img/leo-folder-locker-logo.png

author: "Malik Usman Aura"
social:
  name: Malik Usman Aura
  links:
    - https://twitter.com/malikusmanaura
    - https://www.facebook.com/malikusman.aura
    - https://pk.linkedin.com/in/malikusmanaura
    - https://plus.google.com/+MalikUsmanAura
    - https://github.com/usmanaura47
    - https://sourceforge.net/u/usman47

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  red:       '#d9534f'
  grey:      '#343434'
  amethyst:  '#9b59b6'
  asphalt:   '#34495e'
  sea:       '#e74c3c'

kramdown:
  auto_ids:  false
  
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
